# ------------親-------------
ladys = Category.find_or_create_by(name: "レディース")
mens = Category.find_or_create_by(name: "メンズ")
baby_kids = Category.find_or_create_by(name: "ベビー・キッズ")
interior_life_small_article = Category.find_or_create_by(name: "インテリア・暮らし/小物")
book_music_game = Category.find_or_create_by(name: "本・音楽・ゲーム")
toy_hobby_goods = Category.find_or_create_by(name: "おもちゃ・ホビー・グッズ")
cosmetics_perfume_beauty = Category.find_or_create_by(name: "コスメ・香水・美容")
home_appliance_smartphone_camera = Category.find_or_create_by(name: "家電・スマホ・カメラ")
sports_leisure = Category.find_or_create_by(name: "スポーツ・レジャー")
handmade = Category.find_or_create_by(name: "ハンドメイド")
ticket = Category.find_or_create_by(name: "チケット")
bicycle_motorcycle = Category.find_or_create_by(name: "自転車・オートバイ")
other = Category.find_or_create_by(name: "その他")

# ------------レディース 子--------------
ladys_tops = ladys.children.find_or_create_by(name: "トップス")
ladys_jacket_outer = ladys.children.find_or_create_by(name: "ジャケット/アウター")
ladys_pants = ladys.children.find_or_create_by(name: "パンツ")
ladys_skirt = ladys.children.find_or_create_by(name: "スカート")
ledys_onepiece = ladys.children.find_or_create_by(name: "ワンピース")
ladys_shoes = ladys.children.find_or_create_by(name: "靴")
ladys_roomwear_pajamas = ladys.children.find_or_create_by(name: "ルームウェア/パジャマ")
ladys_legwear = ladys.children.find_or_create_by(name: "レッグウェア")
ladys_hat = ladys.children.find_or_create_by(name: "帽子")
ladys_bag = ladys.children.find_or_create_by(name: "バッグ")
ladys_accessories = ladys.children.find_or_create_by(name: "アクセサリー")
ladys_hair_accessories = ladys.children.find_or_create_by(name: "ヘアアクセサリー")
ladys_small_article = ladys.children.find_or_create_by(name: "小物")
ladys_watch = ladys.children.find_or_create_by(name: "時計")
ladys_wig_extension = ladys.children.find_or_create_by(name: "ウィッグ/エクステ")
ladys_yukata_swimsuit = ladys.children.find_or_create_by(name: "浴衣/水着")
ladys_suit_formal_dress = ladys.children.find_or_create_by(name: "スーツ/フォーマル/ドレス")
ladys_maternity = ladys.children.find_or_create_by(name: "マタニティ")
ladys_other = ladys.children.find_or_create_by(name: "その他")

# -------------レディース 孫--------------
ladys_tops.children.find_or_create_by(name: "Tシャツ/カットソー(半袖/袖なし)")
ladys_tops.children.find_or_create_by(name: "Tシャツ/カットソー(七分/長袖)")
ladys_tops.children.find_or_create_by(name: "シャツ/ブラウス(半袖/袖なし)")
ladys_tops.children.find_or_create_by(name: "シャツ/ブラウス(七分/長袖)")
ladys_tops.children.find_or_create_by(name: "ポロシャツ")
ladys_tops.children.find_or_create_by(name: "キャミソール")
ladys_tops.children.find_or_create_by(name: "タンクトップ")
ladys_tops.children.find_or_create_by(name: "ホルターネック")
ladys_tops.children.find_or_create_by(name: "ニット/セーター")
ladys_tops.children.find_or_create_by(name: "チュニック")
ladys_tops.children.find_or_create_by(name: "カーディガン/ボレロ")
ladys_tops.children.find_or_create_by(name: "アンサンブル")
ladys_tops.children.find_or_create_by(name: "ベスト/ジレ")
ladys_tops.children.find_or_create_by(name: "パーカー")
ladys_tops.children.find_or_create_by(name: "トレーナー/スウェット")
ladys_tops.children.find_or_create_by(name: "ベアトップ/チューブトップ")
ladys_tops.children.find_or_create_by(name: "ジャージ")
ladys_tops.children.find_or_create_by(name: "その他")

ladys_jacket_outer.children.find_or_create_by(name: "テーラードジャケット")
ladys_jacket_outer.children.find_or_create_by(name: "ノーカラージャケット")
ladys_jacket_outer.children.find_or_create_by(name: "Gジャン/デニムジャケット")
ladys_jacket_outer.children.find_or_create_by(name: "レザージャケット")
ladys_jacket_outer.children.find_or_create_by(name: "ダウンジャケット")
ladys_jacket_outer.children.find_or_create_by(name: "ライダースジャケット")
ladys_jacket_outer.children.find_or_create_by(name: "ミリタリージャケット")
ladys_jacket_outer.children.find_or_create_by(name: "ダウンベスト")
ladys_jacket_outer.children.find_or_create_by(name: "ジャンパー/ブルゾン")
ladys_jacket_outer.children.find_or_create_by(name: "ポンチョ")
ladys_jacket_outer.children.find_or_create_by(name: "ロングコート")
ladys_jacket_outer.children.find_or_create_by(name: "トレンチコート")
ladys_jacket_outer.children.find_or_create_by(name: "ダッフルコート")
ladys_jacket_outer.children.find_or_create_by(name: "ピーコート")
ladys_jacket_outer.children.find_or_create_by(name: "チェスターコート")
ladys_jacket_outer.children.find_or_create_by(name: "モッズコート")
ladys_jacket_outer.children.find_or_create_by(name: "スタジャン")
ladys_jacket_outer.children.find_or_create_by(name: "毛皮/ファーコート")
ladys_jacket_outer.children.find_or_create_by(name: "スプロングコート")
ladys_jacket_outer.children.find_or_create_by(name: "スカジャン")
ladys_jacket_outer.children.find_or_create_by(name: "その他")

ladys_pants.children.find_or_create_by(name: "デニム/ジーンズ")
ladys_pants.children.find_or_create_by(name: "ショートパンツ")
ladys_pants.children.find_or_create_by(name: "カジュアルパンツ")
ladys_pants.children.find_or_create_by(name: "ハーフパンツ")
ladys_pants.children.find_or_create_by(name: "チノパン")
ladys_pants.children.find_or_create_by(name: "ワークパンツ/カーゴパンツ")
ladys_pants.children.find_or_create_by(name: "クロップドパンツ")
ladys_pants.children.find_or_create_by(name: "サロペット/オーバーオール")
ladys_pants.children.find_or_create_by(name: "オールインワン")
ladys_pants.children.find_or_create_by(name: "サルエルパンツ")
ladys_pants.children.find_or_create_by(name: "ガウチョパンツ")
ladys_pants.children.find_or_create_by(name: "その他")

ladys_skirt.children.find_or_create_by(name: "ミニスカート")
ladys_skirt.children.find_or_create_by(name: "ひざ丈スカート")
ladys_skirt.children.find_or_create_by(name: "ロングスカート")
ladys_skirt.children.find_or_create_by(name: "キュロット")
ladys_skirt.children.find_or_create_by(name: "その他")

ledys_onepiece.children.find_or_create_by(name: "ミニワンピース")
ledys_onepiece.children.find_or_create_by(name: "ひざ丈ワンピース")
ledys_onepiece.children.find_or_create_by(name: "ロングワンピース")
ledys_onepiece.children.find_or_create_by(name: "その他")

ladys_shoes.children.find_or_create_by(name: "ハイヒール")
ladys_shoes.children.find_or_create_by(name: "ブーツ")
ladys_shoes.children.find_or_create_by(name: "サンダル")
ladys_shoes.children.find_or_create_by(name: "スニーカー")
ladys_shoes.children.find_or_create_by(name: "ミュール")
ladys_shoes.children.find_or_create_by(name: "モカシン")
ladys_shoes.children.find_or_create_by(name: "ローファー/革靴")
ladys_shoes.children.find_or_create_by(name: "フラットシューズ/バレエシューズ")
ladys_shoes.children.find_or_create_by(name: "長靴/レインシューズ")
ladys_shoes.children.find_or_create_by(name: "その他")

ladys_roomwear_pajamas.children.find_or_create_by(name: "パジャマ")
ladys_roomwear_pajamas.children.find_or_create_by(name: "ルームウェア")

ladys_legwear.children.find_or_create_by(name: "ソックス")
ladys_legwear.children.find_or_create_by(name: "スパッツ/レギンス")
ladys_legwear.children.find_or_create_by(name: "ストッキング/タイツ")
ladys_legwear.children.find_or_create_by(name: "レッグウォーマー")
ladys_legwear.children.find_or_create_by(name: "その他")

ladys_hat.children.find_or_create_by(name: "ニットキャップ/ビーニー")
ladys_hat.children.find_or_create_by(name: "ハット")
ladys_hat.children.find_or_create_by(name: "ハンチング/ベレー帽")
ladys_hat.children.find_or_create_by(name: "キャップ")
ladys_hat.children.find_or_create_by(name: "キャスケット")
ladys_hat.children.find_or_create_by(name: "麦わら帽子")
ladys_hat.children.find_or_create_by(name: "その他")

ladys_bag.children.find_or_create_by(name: "ハンドバッグ")
ladys_bag.children.find_or_create_by(name: "トートバッグ")
ladys_bag.children.find_or_create_by(name: "エコバッグ")
ladys_bag.children.find_or_create_by(name: "リュック/バックパック")
ladys_bag.children.find_or_create_by(name: "ボストンバッグ")
ladys_bag.children.find_or_create_by(name: "スポーツバッグ")
ladys_bag.children.find_or_create_by(name: "ショルダーバッグ")
ladys_bag.children.find_or_create_by(name: "クラッチバッグ")
ladys_bag.children.find_or_create_by(name: "ポーチ/バニティ")
ladys_bag.children.find_or_create_by(name: "ボディバッグ/ウェストバッグ")
ladys_bag.children.find_or_create_by(name: "マザーズバッグ")
ladys_bag.children.find_or_create_by(name: "メッセンジャーバッグ")
ladys_bag.children.find_or_create_by(name: "ビジネスバッグ")
ladys_bag.children.find_or_create_by(name: "旅行用バッグ/キャリーバッグ")
ladys_bag.children.find_or_create_by(name: "ショップ袋")
ladys_bag.children.find_or_create_by(name: "和装用バッグ")
ladys_bag.children.find_or_create_by(name: "かごバッグ")
ladys_bag.children.find_or_create_by(name: "その他")

ladys_accessories.children.find_or_create_by(name: "ネックレス")
ladys_accessories.children.find_or_create_by(name: "ブレスレット")
ladys_accessories.children.find_or_create_by(name: "バングル/リストバンド")
ladys_accessories.children.find_or_create_by(name: "リング")
ladys_accessories.children.find_or_create_by(name: "ピアス(片耳用)")
ladys_accessories.children.find_or_create_by(name: "ピアス(両耳用)")
ladys_accessories.children.find_or_create_by(name: "イヤリング")
ladys_accessories.children.find_or_create_by(name: "アンクレット")
ladys_accessories.children.find_or_create_by(name: "ブローチ/コサージュ")
ladys_accessories.children.find_or_create_by(name: "チャーム")
ladys_accessories.children.find_or_create_by(name: "その他")

ladys_hair_accessories.children.find_or_create_by(name: "ヘアゴム/シュシュ")
ladys_hair_accessories.children.find_or_create_by(name: "ヘアバンド/カチューシャ")
ladys_hair_accessories.children.find_or_create_by(name: "ヘアピン")
ladys_hair_accessories.children.find_or_create_by(name: "その他")

ladys_small_article.children.find_or_create_by(name: "長財布")
ladys_small_article.children.find_or_create_by(name: "折り財布")
ladys_small_article.children.find_or_create_by(name: "コインケース/小銭入れ")
ladys_small_article.children.find_or_create_by(name: "名刺入れ/定期入れ")
ladys_small_article.children.find_or_create_by(name: "キーケース")
ladys_small_article.children.find_or_create_by(name: "キーホルダー")
ladys_small_article.children.find_or_create_by(name: "手袋/アームカバー")
ladys_small_article.children.find_or_create_by(name: "ハンカチ")
ladys_small_article.children.find_or_create_by(name: "ベルト")
ladys_small_article.children.find_or_create_by(name: "マフラー/ショール")
ladys_small_article.children.find_or_create_by(name: "ストール/スヌード")
ladys_small_article.children.find_or_create_by(name: "バンダナ/スカーフ")
ladys_small_article.children.find_or_create_by(name: "ネックウォーマー")
ladys_small_article.children.find_or_create_by(name: "サスペンダー")
ladys_small_article.children.find_or_create_by(name: "サングラス/メガネ")
ladys_small_article.children.find_or_create_by(name: "モバイルケース/カバー")
ladys_small_article.children.find_or_create_by(name: "手帳")
ladys_small_article.children.find_or_create_by(name: "イヤマフラー")
ladys_small_article.children.find_or_create_by(name: "傘")
ladys_small_article.children.find_or_create_by(name: "レインコート/ポンチョ")
ladys_small_article.children.find_or_create_by(name: "ミラー")
ladys_small_article.children.find_or_create_by(name: "タバコグッズ")
ladys_small_article.children.find_or_create_by(name: "その他")

ladys_watch.children.find_or_create_by(name: "腕時計(アナログ)")
ladys_watch.children.find_or_create_by(name: "腕時計(デジタル)")
ladys_watch.children.find_or_create_by(name: "ラバーベルト")
ladys_watch.children.find_or_create_by(name: "レザーベルト")
ladys_watch.children.find_or_create_by(name: "金属ベルト")
ladys_watch.children.find_or_create_by(name: "その他")

ladys_wig_extension.children.find_or_create_by(name:"前髪ウィッグ")
ladys_wig_extension.children.find_or_create_by(name:"ロングスカート")
ladys_wig_extension.children.find_or_create_by(name:"ロングカール")
ladys_wig_extension.children.find_or_create_by(name:"ショートストレート")
ladys_wig_extension.children.find_or_create_by(name:"ショートカール")
ladys_wig_extension.children.find_or_create_by(name:"その他")

ladys_yukata_swimsuit.children.find_or_create_by(name: "浴衣")
ladys_yukata_swimsuit.children.find_or_create_by(name: "着物")
ladys_yukata_swimsuit.children.find_or_create_by(name: "振袖")
ladys_yukata_swimsuit.children.find_or_create_by(name: "長襦袢/半襦袢")
ladys_yukata_swimsuit.children.find_or_create_by(name: "水着セパレート")
ladys_yukata_swimsuit.children.find_or_create_by(name: "水着ワンピース")
ladys_yukata_swimsuit.children.find_or_create_by(name: "水着スポーツ用")
ladys_yukata_swimsuit.children.find_or_create_by(name: "その他")

ladys_suit_formal_dress.children.find_or_create_by(name: "スカートスーツ上下")
ladys_suit_formal_dress.children.find_or_create_by(name: "パンツスーツ上下")
ladys_suit_formal_dress.children.find_or_create_by(name: "ドレス")
ladys_suit_formal_dress.children.find_or_create_by(name: "パーティーグッズ")
ladys_suit_formal_dress.children.find_or_create_by(name: "シューズ")
ladys_suit_formal_dress.children.find_or_create_by(name: "ウェディング")
ladys_suit_formal_dress.children.find_or_create_by(name: "その他")

ladys_maternity.children.find_or_create_by(name: "トップス")
ladys_maternity.children.find_or_create_by(name: "アウター")
ladys_maternity.children.find_or_create_by(name: "インナー")
ladys_maternity.children.find_or_create_by(name: "ワンピース")
ladys_maternity.children.find_or_create_by(name: "パンツ/スパッツ")
ladys_maternity.children.find_or_create_by(name: "スカート")
ladys_maternity.children.find_or_create_by(name: "パジャマ")
ladys_maternity.children.find_or_create_by(name: "授乳服")
ladys_maternity.children.find_or_create_by(name: "その他")

ladys_other.children.find_or_create_by(name: "コスプレ")
ladys_other.children.find_or_create_by(name: "下着")
ladys_other.children.find_or_create_by(name: "その他")

# -----------メンズ 子-------------
mens_tops = mens.children.find_or_create_by(name: "トップス")
mens_jacket_outer = mens.children.find_or_create_by(name: "ジャケット/アウター")
mens_pants = mens.children.find_or_create_by(name: "パンツ")
mens_shoes = mens.children.find_or_create_by(name: "靴")
mens_bag = mens.children.find_or_create_by(name: "バッグ")
mens_suit = mens.children.find_or_create_by(name: "スーツ")
mens_hat = mens.children.find_or_create_by(name: "帽子")
mens_accessories = mens.children.find_or_create_by(name: "アクセサリー")
mens_small_article = mens.children.find_or_create_by(name: "小物")
mens_watch = mens.children.find_or_create_by(name: "時計")
mens_swimsuit = mens.children.find_or_create_by(name: "水着")
mens_legwear = mens.children.find_or_create_by(name: "レッグウェア")
mens_underwear = mens.children.find_or_create_by(name: "アンダーウェア")
mens_other = mens.children.find_or_create_by(name: "その他")

# -----------メンズ 孫-------------
mens_tops.children.find_or_create_by(name: "Tシャツ/カットソー(半袖/袖なし)")
mens_tops.children.find_or_create_by(name: "Tシャツ/カットソー(七分/長袖)")
mens_tops.children.find_or_create_by(name: "シャツ")
mens_tops.children.find_or_create_by(name: "ポロシャツ")
mens_tops.children.find_or_create_by(name: "タンクトップ")
mens_tops.children.find_or_create_by(name: "ニット/セーター")
mens_tops.children.find_or_create_by(name: "パーカー")
mens_tops.children.find_or_create_by(name: "カーディガン")
mens_tops.children.find_or_create_by(name: "スウェット")
mens_tops.children.find_or_create_by(name: "ジャージ")
mens_tops.children.find_or_create_by(name: "ベスト")
mens_tops.children.find_or_create_by(name: "その他")

mens_pants.children.find_or_create_by(name: "デニム/ジーンズ")
mens_pants.children.find_or_create_by(name: "ワークパンツ/カーゴパンツ")
mens_pants.children.find_or_create_by(name: "スラックス")
mens_pants.children.find_or_create_by(name: "チノパン")
mens_pants.children.find_or_create_by(name: "ショートパンツ")
mens_pants.children.find_or_create_by(name: "ペインターパンツ")
mens_pants.children.find_or_create_by(name: "サルエルパンツ")
mens_pants.children.find_or_create_by(name: "オーバーオール")
mens_pants.children.find_or_create_by(name: "その他")

mens_shoes.children.find_or_create_by(name: "スニーカー")
mens_shoes.children.find_or_create_by(name: "サンダル")
mens_shoes.children.find_or_create_by(name: "ブーツ")
mens_shoes.children.find_or_create_by(name: "モカシン")
mens_shoes.children.find_or_create_by(name: "ドレス/ビジネス")
mens_shoes.children.find_or_create_by(name: "長靴/レインシューズ")
mens_shoes.children.find_or_create_by(name: "デッキシューズ")
mens_shoes.children.find_or_create_by(name: "その他")

mens_bag.children.find_or_create_by(name: "ショルダーバッグ")
mens_bag.children.find_or_create_by(name: "トートバッグ")
mens_bag.children.find_or_create_by(name: "ボストンバッグ")
mens_bag.children.find_or_create_by(name: "リュック/バックパック")
mens_bag.children.find_or_create_by(name: "ウエストポーチ")
mens_bag.children.find_or_create_by(name: "ボディーバッグ")
mens_bag.children.find_or_create_by(name: "ドラムバッグ")
mens_bag.children.find_or_create_by(name: "ビジネスバッグ")
mens_bag.children.find_or_create_by(name: "トラベルバッグ")
mens_bag.children.find_or_create_by(name: "メッセンジャーバッグ")
mens_bag.children.find_or_create_by(name: "エコバッグ")
mens_bag.children.find_or_create_by(name: "その他")

mens_suit.children.find_or_create_by(name: "スーツジャケット")
mens_suit.children.find_or_create_by(name: "スーツベスト")
mens_suit.children.find_or_create_by(name: "スラックス")
mens_suit.children.find_or_create_by(name: "セットアップ")
mens_suit.children.find_or_create_by(name: "その他")

mens_hat.children.find_or_create_by(name: "キャップ")
mens_hat.children.find_or_create_by(name: "ハット")
mens_hat.children.find_or_create_by(name: "ニットキャップ/ビーニー")
mens_hat.children.find_or_create_by(name: "ハンチング/ベレー帽")
mens_hat.children.find_or_create_by(name: "キャスケット")
mens_hat.children.find_or_create_by(name: "サンバイザー")
mens_hat.children.find_or_create_by(name: "その他")

mens_accessories.children.find_or_create_by(name: "ネックレス")
mens_accessories.children.find_or_create_by(name: "ブレスレット")
mens_accessories.children.find_or_create_by(name: "バングル/リストバンド")
mens_accessories.children.find_or_create_by(name: "リング")
mens_accessories.children.find_or_create_by(name: "ピアス(片耳用)")
mens_accessories.children.find_or_create_by(name: "ピアス(両耳用)")
mens_accessories.children.find_or_create_by(name: "アンクレット")
mens_accessories.children.find_or_create_by(name: "その他")

mens_small_article.children.find_or_create_by(name: "長財布")
mens_small_article.children.find_or_create_by(name: "折り財布")
mens_small_article.children.find_or_create_by(name: "マネークリップ")
mens_small_article.children.find_or_create_by(name: "コインケース/小銭入れ")
mens_small_article.children.find_or_create_by(name: "名刺入れ/定期入れ")
mens_small_article.children.find_or_create_by(name: "キーケース")
mens_small_article.children.find_or_create_by(name: "キーホルダー")
mens_small_article.children.find_or_create_by(name: "ネクタイ")
mens_small_article.children.find_or_create_by(name: "手袋")
mens_small_article.children.find_or_create_by(name: "ハンカチ")
mens_small_article.children.find_or_create_by(name: "ベルト")
mens_small_article.children.find_or_create_by(name: "マフラー")
mens_small_article.children.find_or_create_by(name: "ストール")
mens_small_article.children.find_or_create_by(name: "バンダナ")
mens_small_article.children.find_or_create_by(name: "ネックウォーマー")
mens_small_article.children.find_or_create_by(name: "サスペンダー")
mens_small_article.children.find_or_create_by(name: "ウォレットチェーン")
mens_small_article.children.find_or_create_by(name: "サングラス/メガネ")
mens_small_article.children.find_or_create_by(name: "モバイルケース/カバー")
mens_small_article.children.find_or_create_by(name: "手帳")
mens_small_article.children.find_or_create_by(name: "ストラップ")
mens_small_article.children.find_or_create_by(name: "ネクタイピン")
mens_small_article.children.find_or_create_by(name: "カフリンクス")
mens_small_article.children.find_or_create_by(name: "イヤマフラー")
mens_small_article.children.find_or_create_by(name: "傘")
mens_small_article.children.find_or_create_by(name: "レインコート")
mens_small_article.children.find_or_create_by(name: "ミラー")
mens_small_article.children.find_or_create_by(name: "タバコグッズ")
mens_small_article.children.find_or_create_by(name: "その他")

mens_watch.children.find_or_create_by(name: "腕時計(アナログ)")
mens_watch.children.find_or_create_by(name: "腕時計(デジタル)")
mens_watch.children.find_or_create_by(name: "ラバーベルト")
mens_watch.children.find_or_create_by(name: "レザーベルト")
mens_watch.children.find_or_create_by(name: "金属ベルト")
mens_watch.children.find_or_create_by(name: "その他")

mens_swimsuit.children.find_or_create_by(name: "一般水着")
mens_swimsuit.children.find_or_create_by(name: "スポーツ用")
mens_swimsuit.children.find_or_create_by(name: "アクセサリー")
mens_swimsuit.children.find_or_create_by(name: "その他")

mens_legwear.children.find_or_create_by(name: "ソックス")
mens_legwear.children.find_or_create_by(name: "レギンス/スパッツ")
mens_legwear.children.find_or_create_by(name: "レッグウォーマー")
mens_legwear.children.find_or_create_by(name: "その他")

mens_underwear.children.find_or_create_by(name: "トランクス")
mens_underwear.children.find_or_create_by(name: "ボクサーパンツ")
mens_underwear.children.find_or_create_by(name: "その他")

# --------ベビー・キッズ 子-------------
baby_clothes_girl = baby_kids.children.find_or_create_by(name: "ベビー服(女の子用) ~95cm")
baby_clothes_boy = baby_kids.children.find_or_create_by(name: "ベビー服(男の子用) ~95cm")
baby_clothes_unisex = baby_kids.children.find_or_create_by(name: "ベビー服(男女兼用) ~95cm")
kids_clothes_girl = baby_kids.children.find_or_create_by(name: "キッズ服(女の子用) ~100cm")
kids_clothes_boy = baby_kids.children.find_or_create_by(name: "キッズ服(男の子用) ~100cm")
kids_clothes_unisex = baby_kids.children.find_or_create_by(name: "キッズ服(男女兼用) ~100cm")
kids_shoes = baby_kids.children.find_or_create_by(name: "キッズ靴")
kids_fashion_small_article = baby_kids.children.find_or_create_by(name: "子ども用ファッション小物")
kids_omutu_toilet_bath = baby_kids.children.find_or_create_by(name: "おむつ/トイレ/バス")
kids_move = baby_kids.children.find_or_create_by(name: "外出/移動")
kids_meal = baby_kids.children.find_or_create_by(name: "授乳/食事")
baby_furniture_bedding = baby_kids.children.find_or_create_by(name: "ベビー家具/寝具/室内用品")
kids_toy = baby_kids.children.find_or_create_by(name: "おもちゃ")
kids_event = baby_kids.children.find_or_create_by(name: "行事/記念品")
kids_other = baby_kids.children.find_or_create_by(name: "その他")

# -------ベビー・キッズ 孫----------
baby_clothes_girl.children.find_or_create_by(name: "トップス")
baby_clothes_girl.children.find_or_create_by(name: "アウター")
baby_clothes_girl.children.find_or_create_by(name: "パンツ")
baby_clothes_girl.children.find_or_create_by(name: "スカート")
baby_clothes_girl.children.find_or_create_by(name: "ワンピース")
baby_clothes_girl.children.find_or_create_by(name: "ベビードレス")
baby_clothes_girl.children.find_or_create_by(name: "おくるみ")
baby_clothes_girl.children.find_or_create_by(name: "下着/肌着")
baby_clothes_girl.children.find_or_create_by(name: "パジャマ")
baby_clothes_girl.children.find_or_create_by(name: "ロンパース")
baby_clothes_girl.children.find_or_create_by(name: "その他")

baby_clothes_boy.children.find_or_create_by(name: "トップス")
baby_clothes_boy.children.find_or_create_by(name: "アウター")
baby_clothes_boy.children.find_or_create_by(name: "パンツ")
baby_clothes_boy.children.find_or_create_by(name: "おくるみ")
baby_clothes_boy.children.find_or_create_by(name: "下着/肌着")
baby_clothes_boy.children.find_or_create_by(name: "パジャマ")
baby_clothes_boy.children.find_or_create_by(name: "ロンパース")
baby_clothes_boy.children.find_or_create_by(name: "その他")

baby_clothes_unisex.children.find_or_create_by(name: "トップス")
baby_clothes_unisex.children.find_or_create_by(name: "アウター")
baby_clothes_unisex.children.find_or_create_by(name: "パンツ")
baby_clothes_unisex.children.find_or_create_by(name: "おくるみ")
baby_clothes_unisex.children.find_or_create_by(name: "下着/肌着")
baby_clothes_unisex.children.find_or_create_by(name: "パジャマ")
baby_clothes_unisex.children.find_or_create_by(name: "ロンパース")
baby_clothes_unisex.children.find_or_create_by(name: "その他")

kids_clothes_girl.children.find_or_create_by(name: "コート")
kids_clothes_girl.children.find_or_create_by(name: "ジャケット/上着")
kids_clothes_girl.children.find_or_create_by(name: "トップス(Tシャツ/カットソー)")
kids_clothes_girl.children.find_or_create_by(name: "トップス(トレーナー)")
kids_clothes_girl.children.find_or_create_by(name: "トップス(チュニック)")
kids_clothes_girl.children.find_or_create_by(name: "トップス(タンクトップ)")
kids_clothes_girl.children.find_or_create_by(name: "トップス(その他)")
kids_clothes_girl.children.find_or_create_by(name: "スカート")
kids_clothes_girl.children.find_or_create_by(name: "パンツ")
kids_clothes_girl.children.find_or_create_by(name: "ワンピース")
kids_clothes_girl.children.find_or_create_by(name: "セットアップ")
kids_clothes_girl.children.find_or_create_by(name: "パジャマ")
kids_clothes_girl.children.find_or_create_by(name: "フォーマル/ドレス")
kids_clothes_girl.children.find_or_create_by(name: "和服")
kids_clothes_girl.children.find_or_create_by(name: "浴衣")
kids_clothes_girl.children.find_or_create_by(name: "甚平")
kids_clothes_girl.children.find_or_create_by(name: "その他")

kids_clothes_boy.children.find_or_create_by(name: "コート")
kids_clothes_boy.children.find_or_create_by(name: "ジャケット/上着")
kids_clothes_boy.children.find_or_create_by(name: "トップス(Tシャツ/カットソー)")
kids_clothes_boy.children.find_or_create_by(name: "トップス(トレーナー)")
kids_clothes_boy.children.find_or_create_by(name: "トップス(その他)")
kids_clothes_boy.children.find_or_create_by(name: "パンツ")
kids_clothes_boy.children.find_or_create_by(name: "セットアップ")
kids_clothes_boy.children.find_or_create_by(name: "パジャマ")
kids_clothes_boy.children.find_or_create_by(name: "フォーマル/ドレス")
kids_clothes_boy.children.find_or_create_by(name: "和服")
kids_clothes_boy.children.find_or_create_by(name: "浴衣")
kids_clothes_boy.children.find_or_create_by(name: "甚平")
kids_clothes_boy.children.find_or_create_by(name: "水着")
kids_clothes_boy.children.find_or_create_by(name: "その他")

kids_clothes_unisex.children.find_or_create_by(name: "コート")
kids_clothes_unisex.children.find_or_create_by(name: "ジャケット/上着")
kids_clothes_unisex.children.find_or_create_by(name: "トップス(Tシャツ/カットソー)")
kids_clothes_unisex.children.find_or_create_by(name: "トップス(トレーナー)")
kids_clothes_unisex.children.find_or_create_by(name: "トップス(その他)")
kids_clothes_unisex.children.find_or_create_by(name: "ボトムス")
kids_clothes_unisex.children.find_or_create_by(name: "パジャマ")
kids_clothes_unisex.children.find_or_create_by(name: "その他")

kids_shoes.children.find_or_create_by(name: "スニーカー")
kids_shoes.children.find_or_create_by(name: "サンダル")
kids_shoes.children.find_or_create_by(name: "ブーツ")
kids_shoes.children.find_or_create_by(name: "長靴")
kids_shoes.children.find_or_create_by(name: "その他")

kids_fashion_small_article.children.find_or_create_by(name: "靴下/スパッツ")
kids_fashion_small_article.children.find_or_create_by(name: "帽子")
kids_fashion_small_article.children.find_or_create_by(name: "エプロン")
kids_fashion_small_article.children.find_or_create_by(name: "サスペンダー")
kids_fashion_small_article.children.find_or_create_by(name: "タイツ")
kids_fashion_small_article.children.find_or_create_by(name: "ハンカチ")
kids_fashion_small_article.children.find_or_create_by(name: "バンダナ")
kids_fashion_small_article.children.find_or_create_by(name: "ベルト")
kids_fashion_small_article.children.find_or_create_by(name: "マフラー")
kids_fashion_small_article.children.find_or_create_by(name: "傘")
kids_fashion_small_article.children.find_or_create_by(name: "手袋")
kids_fashion_small_article.children.find_or_create_by(name: "スタイ")
kids_fashion_small_article.children.find_or_create_by(name: "バッグ")
kids_fashion_small_article.children.find_or_create_by(name: "その他")

kids_omutu_toilet_bath .children.find_or_create_by(name: "おむつ用品")
kids_omutu_toilet_bath .children.find_or_create_by(name: "おまる/補助便座")
kids_omutu_toilet_bath .children.find_or_create_by(name: "トレーニングパンツ")
kids_omutu_toilet_bath .children.find_or_create_by(name: "ベビーバス")
kids_omutu_toilet_bath .children.find_or_create_by(name: "お風呂用品")
kids_omutu_toilet_bath .children.find_or_create_by(name: "その他")

kids_move.children.find_or_create_by(name: "ベビーカー")
kids_move.children.find_or_create_by(name: "抱っこひも/スリング")
kids_move.children.find_or_create_by(name: "チャイルドシート")
kids_move.children.find_or_create_by(name: "その他")

kids_meal.children.find_or_create_by(name: "ミルク")
kids_meal.children.find_or_create_by(name: "ベビーフード")
kids_meal.children.find_or_create_by(name: "ベビー用食器")
kids_meal.children.find_or_create_by(name: "その他")

baby_furniture_bedding.children.find_or_create_by(name: "ベッド")
baby_furniture_bedding.children.find_or_create_by(name: "布団/毛布")
baby_furniture_bedding.children.find_or_create_by(name: "イス")
baby_furniture_bedding.children.find_or_create_by(name: "たんす")
baby_furniture_bedding.children.find_or_create_by(name: "その他")

kids_toy.children.find_or_create_by(name: "おふろのおもちゃ")
kids_toy.children.find_or_create_by(name: "がらがら")
kids_toy.children.find_or_create_by(name: "オルゴール")
kids_toy.children.find_or_create_by(name: "ベビージム")
kids_toy.children.find_or_create_by(name: "手押し車/カタカタ")
kids_toy.children.find_or_create_by(name: "知育玩具")
kids_toy.children.find_or_create_by(name: "その他")

kids_event.children.find_or_create_by(name: "お宮参り用品")
kids_event.children.find_or_create_by(name: "お食い初め用品")
kids_event.children.find_or_create_by(name: "アルバム")
kids_event.children.find_or_create_by(name: "手形/足形")
kids_event.children.find_or_create_by(name: "その他")

kids_other.children.find_or_create_by(name: "母子手帳用品")
kids_other.children.find_or_create_by(name: "その他")

# ----------インテリア・住まい・小物 子-------------
interior_kitchen_tableware = interior_life_small_article.children.find_or_create_by(name: "キッチン/食器")
interior_bed_mattress = interior_life_small_article.children.find_or_create_by(name: "ベッド/マットレス")
interior_sofa_sofabed = interior_life_small_article.children.find_or_create_by(name: "ソファ/ベッド")
interior_chair = interior_life_small_article.children.find_or_create_by(name: "椅子/チェア")
interior_desk_table = interior_life_small_article.children.find_or_create_by(name: "机/チェア")
interior_storage_furniture = interior_life_small_article.children.find_or_create_by(name: "収納家具")
interior_rug_carpet_matt = interior_life_small_article.children.find_or_create_by(name: "ラグ/カーペット/マット")
interior_curtain_blind = interior_life_small_article.children.find_or_create_by(name: "カーテン/ブラインド")
interior_light = interior_life_small_article.children.find_or_create_by(name: "ライト/照明")
interior_bedding = interior_life_small_article.children.find_or_create_by(name: "寝具")
interior_small_article = interior_life_small_article.children.find_or_create_by(name: "インテリア小物")
interior_seoson = interior_life_small_article.children.find_or_create_by(name: "季節/年中行事")
interior_other = interior_life_small_article.children.find_or_create_by(name: "その他")

# ----------インテリア・住まい・小物 孫-------------
interior_kitchen_tableware.children.find_or_create_by(name: "食器")
interior_kitchen_tableware.children.find_or_create_by(name: "調理器具")
interior_kitchen_tableware.children.find_or_create_by(name: "収納/キッチン雑貨")
interior_kitchen_tableware.children.find_or_create_by(name: "弁当用品")
interior_kitchen_tableware.children.find_or_create_by(name: "カラトリー(スプーン等)")
interior_kitchen_tableware.children.find_or_create_by(name: "テーブル用品")
interior_kitchen_tableware.children.find_or_create_by(name: "容器")
interior_kitchen_tableware.children.find_or_create_by(name: "エプロン")
interior_kitchen_tableware.children.find_or_create_by(name: "アルコールグッズ")
interior_kitchen_tableware.children.find_or_create_by(name: "浄水器")
interior_kitchen_tableware.children.find_or_create_by(name: "その他")

interior_bed_mattress.children.find_or_create_by(name: "セミシングルベッド")
interior_bed_mattress.children.find_or_create_by(name: "シングルベッド")
interior_bed_mattress.children.find_or_create_by(name: "セミダブルベッド")
interior_bed_mattress.children.find_or_create_by(name: "ダブルベッド")
interior_bed_mattress.children.find_or_create_by(name: "ワイドダブルベッド")
interior_bed_mattress.children.find_or_create_by(name: "クイーンベッド")
interior_bed_mattress.children.find_or_create_by(name: "キングベッド")
interior_bed_mattress.children.find_or_create_by(name: "脚付きマッドレスベッド")
interior_bed_mattress.children.find_or_create_by(name: "マットレス")
interior_bed_mattress.children.find_or_create_by(name: "すのこベッド")
interior_bed_mattress.children.find_or_create_by(name: "ロフトベッド/システムベッド")
interior_bed_mattress.children.find_or_create_by(name: "簡易ベッド/折りたたみベッド")
interior_bed_mattress.children.find_or_create_by(name: "収納付き")
interior_bed_mattress.children.find_or_create_by(name: "その他")

interior_sofa_sofabed.children.find_or_create_by(name: "ソファセット")
interior_sofa_sofabed.children.find_or_create_by(name: "シングルベッド")
interior_sofa_sofabed.children.find_or_create_by(name: "ラブソファ")
interior_sofa_sofabed.children.find_or_create_by(name: "トリプルソファ")
interior_sofa_sofabed.children.find_or_create_by(name: "オットマン")
interior_sofa_sofabed.children.find_or_create_by(name: "コーナーソファ")
interior_sofa_sofabed.children.find_or_create_by(name: "ビーズソファ/クッションソファ")
interior_sofa_sofabed.children.find_or_create_by(name: "ローソファ/フロアソファ")
interior_sofa_sofabed.children.find_or_create_by(name: "ソファベッド")
interior_sofa_sofabed.children.find_or_create_by(name: "応接セット")
interior_sofa_sofabed.children.find_or_create_by(name: "ソファカバー")
interior_sofa_sofabed.children.find_or_create_by(name: "リクライニングソファ")
interior_sofa_sofabed.children.find_or_create_by(name: "その他")

interior_chair.children.find_or_create_by(name: "一般")
interior_chair.children.find_or_create_by(name: "スツール")
interior_chair.children.find_or_create_by(name: "ダイニングチェア")
interior_chair.children.find_or_create_by(name: "ハイバックチェア")
interior_chair.children.find_or_create_by(name: "ロッキングチェア")
interior_chair.children.find_or_create_by(name: "座椅子")
interior_chair.children.find_or_create_by(name: "折りたたみ椅子")
interior_chair.children.find_or_create_by(name: "デスクチェア")
interior_chair.children.find_or_create_by(name: "その他")

interior_desk_table.children.find_or_create_by(name: "こたつ")
interior_desk_table.children.find_or_create_by(name: "カウンターテーブル")
interior_desk_table.children.find_or_create_by(name: "サイドテーブル")
interior_desk_table.children.find_or_create_by(name: "センターテーブル")
interior_desk_table.children.find_or_create_by(name: "ダイニングテーブル")
interior_desk_table.children.find_or_create_by(name: "座卓/ちゃぶ台")
interior_desk_table.children.find_or_create_by(name: "アウトドア用")
interior_desk_table.children.find_or_create_by(name: "パソコン用")
interior_desk_table.children.find_or_create_by(name: "事務机/学習机")
interior_desk_table.children.find_or_create_by(name: "その他")

interior_storage_furniture.children.find_or_create_by(name: "リビング収納")
interior_storage_furniture.children.find_or_create_by(name: "キッチン収納")
interior_storage_furniture.children.find_or_create_by(name: "玄関/屋外収納")
interior_storage_furniture.children.find_or_create_by(name: "バス/トイレ用品")
interior_storage_furniture.children.find_or_create_by(name: "本収納")
interior_storage_furniture.children.find_or_create_by(name: "本/CD/DVD収納")
interior_storage_furniture.children.find_or_create_by(name: "洋服タンス/押入れ収納")
interior_storage_furniture.children.find_or_create_by(name: "電話台/ファックス台")
interior_storage_furniture.children.find_or_create_by(name: "ドレッサー/鏡台")
interior_storage_furniture.children.find_or_create_by(name: "棚/ラック")
interior_storage_furniture.children.find_or_create_by(name: "ケース/ボックス")
interior_storage_furniture.children.find_or_create_by(name: "その他")

interior_rug_carpet_matt.children.find_or_create_by(name: "ラグ")
interior_rug_carpet_matt.children.find_or_create_by(name: "カーペット")
interior_rug_carpet_matt.children.find_or_create_by(name: "ホットカーペット")
interior_rug_carpet_matt.children.find_or_create_by(name: "玄関/キッチンマット")
interior_rug_carpet_matt.children.find_or_create_by(name: "トイレ/バスマット")
interior_rug_carpet_matt.children.find_or_create_by(name: "その他")

interior_curtain_blind.children.find_or_create_by(name: "カーテン")
interior_curtain_blind.children.find_or_create_by(name: "ブラインド")
interior_curtain_blind.children.find_or_create_by(name: "ロールスクリーン")
interior_curtain_blind.children.find_or_create_by(name: "のれん")
interior_curtain_blind.children.find_or_create_by(name: "その他")

interior_light.children.find_or_create_by(name: "蛍光灯/電球")
interior_light.children.find_or_create_by(name: "天井照明")
interior_light.children.find_or_create_by(name: "フロアスタンド")
interior_light.children.find_or_create_by(name: "その他")

interior_bedding.children.find_or_create_by(name: "布団/毛布")
interior_bedding.children.find_or_create_by(name: "枕")
interior_bedding.children.find_or_create_by(name: "シーツ/カバー")
interior_bedding.children.find_or_create_by(name: "その他")


interior_small_article.children.find_or_create_by(name: "ごみ箱")
interior_small_article.children.find_or_create_by(name: "ウェルカムボード")
interior_small_article.children.find_or_create_by(name: "オルゴール")
interior_small_article.children.find_or_create_by(name: "クッション")
interior_small_article.children.find_or_create_by(name: "クッションカバー")
interior_small_article.children.find_or_create_by(name: "スリッパラック")
interior_small_article.children.find_or_create_by(name: "ティッシュボックス")
interior_small_article.children.find_or_create_by(name: "バスケット/かご")
interior_small_article.children.find_or_create_by(name: "フォトフレーム")
interior_small_article.children.find_or_create_by(name: "マガジンラック")
interior_small_article.children.find_or_create_by(name: "モビール")
interior_small_article.children.find_or_create_by(name: "花瓶")
interior_small_article.children.find_or_create_by(name: "灰皿")
interior_small_article.children.find_or_create_by(name: "傘立て")
interior_small_article.children.find_or_create_by(name: "小物入れ")
interior_small_article.children.find_or_create_by(name: "置時計")
interior_small_article.children.find_or_create_by(name: "掛時計/柱時計")
interior_small_article.children.find_or_create_by(name: "鏡(立て掛け式)")
interior_small_article.children.find_or_create_by(name: "鏡(壁掛け式))")
interior_small_article.children.find_or_create_by(name: "置物")
interior_small_article.children.find_or_create_by(name: "風鈴")
interior_small_article.children.find_or_create_by(name: "植物/観葉植物")
interior_small_article.children.find_or_create_by(name: "その他")

interior_seoson.children.find_or_create_by(name: "正月")
interior_seoson.children.find_or_create_by(name: "成人式")
interior_seoson.children.find_or_create_by(name: "バレンタインデー")
interior_seoson.children.find_or_create_by(name: "ひな祭り")
interior_seoson.children.find_or_create_by(name: "子どもの日")
interior_seoson.children.find_or_create_by(name: "母の日")
interior_seoson.children.find_or_create_by(name: "父の日")
interior_seoson.children.find_or_create_by(name: "サマーギフト/お中元")
interior_seoson.children.find_or_create_by(name: "夏/夏休み")
interior_seoson.children.find_or_create_by(name: "ハロウィン")
interior_seoson.children.find_or_create_by(name: "敬老の日")
interior_seoson.children.find_or_create_by(name: "七五三")
interior_seoson.children.find_or_create_by(name: "お歳暮")
interior_seoson.children.find_or_create_by(name: "クリスマス")
interior_seoson.children.find_or_create_by(name: "冬一般")
interior_seoson.children.find_or_create_by(name: "その他")

# ---------本・音楽・ゲーム 子-----------
book = book_music_game.children.find_or_create_by(name: "本")
manga = book_music_game.children.find_or_create_by(name: "漫画")
magazine = book_music_game.children.find_or_create_by(name: "雑誌")
cd = book_music_game.children.find_or_create_by(name: "CD")
dvd_blueray = book_music_game.children.find_or_create_by(name: "DVD/ブルーレイ")
record = book_music_game.children.find_or_create_by(name: "レコード")
tv_game = book_music_game.children.find_or_create_by(name: "テレビゲーム")

# ---------本・音楽・ゲーム 孫-----------
book.children.find_or_create_by(name: "文学/小説")
book.children.find_or_create_by(name: "人文/社会")
book.children.find_or_create_by(name: "ノンフィクション/教養")
book.children.find_or_create_by(name: "地図/旅行ガイド")
book.children.find_or_create_by(name: "ビジネス/経済")
book.children.find_or_create_by(name: "健康/医学")
book.children.find_or_create_by(name: "コンピュータ/IT")
book.children.find_or_create_by(name: "趣味/スポーツ/実用")
book.children.find_or_create_by(name: "住まい/暮らし/子育て")
book.children.find_or_create_by(name: "アート/エンタメ")
book.children.find_or_create_by(name: "洋書")
book.children.find_or_create_by(name: "絵本")
book.children.find_or_create_by(name: "参考書")
book.children.find_or_create_by(name: "その他")

manga.children.find_or_create_by(name: "全巻セット")
manga.children.find_or_create_by(name: "少年漫画")
manga.children.find_or_create_by(name: "少女漫画")
manga.children.find_or_create_by(name: "青年漫画")
manga.children.find_or_create_by(name: "女性漫画")
manga.children.find_or_create_by(name: "同人誌")
manga.children.find_or_create_by(name: "その他")

magazine.children.find_or_create_by(name: "アート/エンタメ/ホビー")
magazine.children.find_or_create_by(name: "ファッション")
magazine.children.find_or_create_by(name: "ニュース/総合")
magazine.children.find_or_create_by(name: "趣味/スポーツ")
magazine.children.find_or_create_by(name: "その他")

cd.children.find_or_create_by(name: "邦楽")
cd.children.find_or_create_by(name: "洋楽")
cd.children.find_or_create_by(name: "アニメ")
cd.children.find_or_create_by(name: "クラシック")
cd.children.find_or_create_by(name: "K-POP/アジア")
cd.children.find_or_create_by(name: "キッズ/ファミリー")
cd.children.find_or_create_by(name: "その他")

dvd_blueray.children.find_or_create_by(name: "外国映画")
dvd_blueray.children.find_or_create_by(name: "日本映画")
dvd_blueray.children.find_or_create_by(name: "アニメ")
dvd_blueray.children.find_or_create_by(name: "TVドラマ")
dvd_blueray.children.find_or_create_by(name: "ミュージック")
dvd_blueray.children.find_or_create_by(name: "お笑い/バラエティ")
dvd_blueray.children.find_or_create_by(name: "スポーツ/フィットネス")
dvd_blueray.children.find_or_create_by(name: "キッズ/ファミリー")
dvd_blueray.children.find_or_create_by(name: "その他")

record.children.find_or_create_by(name: "邦楽")
record.children.find_or_create_by(name: "洋楽")
record.children.find_or_create_by(name: "その他")

tv_game.children.find_or_create_by(name: "家庭用ゲーム本体")
tv_game.children.find_or_create_by(name: "家庭用ゲームソフト")
tv_game.children.find_or_create_by(name: "携帯用ゲーム本体")
tv_game.children.find_or_create_by(name: "携帯用ゲームソフト")
tv_game.children.find_or_create_by(name: "PCゲーム")
tv_game.children.find_or_create_by(name: "その他")

# ---------おもちゃ・ホビー・グッズ 子-----------
toy_toy = toy_hobby_goods.children.find_or_create_by(name: "おもちゃ")
toy_talent_goods = toy_hobby_goods.children.find_or_create_by(name: "タレントグッズ")
toy_comic_anime_goods = toy_hobby_goods.children.find_or_create_by(name: "コミック/アニメグッズ")
toy_trading_cards = toy_hobby_goods.children.find_or_create_by(name: "トレーディングカード")
toy_figure = toy_hobby_goods.children.find_or_create_by(name: "フィギュア")
toy_musical_instrument = toy_hobby_goods.children.find_or_create_by(name: "楽器/器材")
toy_collection = toy_hobby_goods.children.find_or_create_by(name: "コレクション")
toy_military = toy_hobby_goods.children.find_or_create_by(name: "ミリタリー")
toy_art = toy_hobby_goods.children.find_or_create_by(name: "美術品")
toy_art_article = toy_hobby_goods.children.find_or_create_by(name: "アート用品")
toy_other = toy_hobby_goods.children.find_or_create_by(name: "その他")

# ---------おもちゃ・ホビー・グッズ 孫-----------
toy_toy.children.find_or_create_by(name: "キャラクターグッズ")
toy_toy.children.find_or_create_by(name: "ぬいぐるみ")
toy_toy.children.find_or_create_by(name: "小物/アクセサリー")
toy_toy.children.find_or_create_by(name: "模型/プラモデル")
toy_toy.children.find_or_create_by(name: "ミニカー")
toy_toy.children.find_or_create_by(name: "トイラジコン")
toy_toy.children.find_or_create_by(name: "プラモデル")
toy_toy.children.find_or_create_by(name: "ホビーラジコン")
toy_toy.children.find_or_create_by(name: "鉄道模型")
toy_toy.children.find_or_create_by(name: "その他")

toy_talent_goods.children.find_or_create_by(name: "アイドル")
toy_talent_goods.children.find_or_create_by(name: "ミュージシャン")
toy_talent_goods.children.find_or_create_by(name: "タレント/お笑い芸人")
toy_talent_goods.children.find_or_create_by(name: "スポーツ選手")
toy_talent_goods.children.find_or_create_by(name: "その他")

toy_comic_anime_goods.children.find_or_create_by(name: "ストラップ")
toy_comic_anime_goods.children.find_or_create_by(name: "キーホルダー")
toy_comic_anime_goods.children.find_or_create_by(name: "バッジ")
toy_comic_anime_goods.children.find_or_create_by(name: "カード")
toy_comic_anime_goods.children.find_or_create_by(name: "クリアファイル")
toy_comic_anime_goods.children.find_or_create_by(name: "ポスター")
toy_comic_anime_goods.children.find_or_create_by(name: "タオル")
toy_comic_anime_goods.children.find_or_create_by(name: "その他")

toy_trading_cards.children.find_or_create_by(name: "遊戯王")
toy_trading_cards.children.find_or_create_by(name: "マジック・ザ・ギャリング")
toy_trading_cards.children.find_or_create_by(name: "ポケモンカードゲーム")
toy_trading_cards.children.find_or_create_by(name: "デュエルマスターズ")
toy_trading_cards.children.find_or_create_by(name: "バトルスピリッツ")
toy_trading_cards.children.find_or_create_by(name: "プリパラ")
toy_trading_cards.children.find_or_create_by(name: "アイカツ")
toy_trading_cards.children.find_or_create_by(name: "カードファイト!!ヴァンガード")
toy_trading_cards.children.find_or_create_by(name: "ヴァイスシュヴァルツ")
toy_trading_cards.children.find_or_create_by(name: "プロ野球オーナーズリーグ")
toy_trading_cards.children.find_or_create_by(name: "ベースボールヒーローズ")
toy_trading_cards.children.find_or_create_by(name: "ドラゴンボール")
toy_trading_cards.children.find_or_create_by(name: "スリーブ")
toy_trading_cards.children.find_or_create_by(name: "その他")

toy_figure.children.find_or_create_by(name: "コミック/アニメ")
toy_figure.children.find_or_create_by(name: "特撮")
toy_figure.children.find_or_create_by(name: "ゲームキャラクター")
toy_figure.children.find_or_create_by(name: "SF/ファンタジー/ホラー")
toy_figure.children.find_or_create_by(name: "アメコミ")
toy_figure.children.find_or_create_by(name: "スポーツ")
toy_figure.children.find_or_create_by(name: "ミリタリー")
toy_figure.children.find_or_create_by(name: "その他")

toy_musical_instrument.children.find_or_create_by(name: "エレキギター")
toy_musical_instrument.children.find_or_create_by(name: "アコースティックギター")
toy_musical_instrument.children.find_or_create_by(name: "ベース")
toy_musical_instrument.children.find_or_create_by(name: "エフェクター")
toy_musical_instrument.children.find_or_create_by(name: "アンプ")
toy_musical_instrument.children.find_or_create_by(name: "弦楽器")
toy_musical_instrument.children.find_or_create_by(name: "管楽器")
toy_musical_instrument.children.find_or_create_by(name: "鍵盤楽器")
toy_musical_instrument.children.find_or_create_by(name: "打楽器")
toy_musical_instrument.children.find_or_create_by(name: "和楽器")
toy_musical_instrument.children.find_or_create_by(name: "楽譜/スコア")
toy_musical_instrument.children.find_or_create_by(name: "レコーディング/PA楽器")
toy_musical_instrument.children.find_or_create_by(name: "DJ機器")
toy_musical_instrument.children.find_or_create_by(name: "DTM/DAW")
toy_musical_instrument.children.find_or_create_by(name: "その他")

toy_collection.children.find_or_create_by(name: "武具")
toy_collection.children.find_or_create_by(name: "使用済切手/官製はがき")
toy_collection.children.find_or_create_by(name: "旧貨幣/金貨/銀貨/記念硬貨")
toy_collection.children.find_or_create_by(name: "印刷物")
toy_collection.children.find_or_create_by(name: "ノベルティグッズ")
toy_collection.children.find_or_create_by(name: "その他")

toy_military.children.find_or_create_by(name: "トイガン")
toy_military.children.find_or_create_by(name: "個人装備")
toy_military.children.find_or_create_by(name: "その他")

toy_art.children.find_or_create_by(name: "陶芸")
toy_art.children.find_or_create_by(name: "ガラス")
toy_art.children.find_or_create_by(name: "漆芸")
toy_art.children.find_or_create_by(name: "金属工芸")
toy_art.children.find_or_create_by(name: "絵画/タペストリ")
toy_art.children.find_or_create_by(name: "版画")
toy_art.children.find_or_create_by(name: "彫刻/オブジェクト")
toy_art.children.find_or_create_by(name: "書")
toy_art.children.find_or_create_by(name: "写真")
toy_art.children.find_or_create_by(name: "その他")

toy_art_article.children.find_or_create_by(name: "画材")
toy_art_article.children.find_or_create_by(name: "額縁")
toy_art_article.children.find_or_create_by(name: "その他")

toy_other.children.find_or_create_by(name: "トランプ/UNO")
toy_other.children.find_or_create_by(name: "カルタ/百人一首")
toy_other.children.find_or_create_by(name: "ダーツ")
toy_other.children.find_or_create_by(name: "ビリヤード")
toy_other.children.find_or_create_by(name: "麻雀")
toy_other.children.find_or_create_by(name: "パズル/ジグソーパズル")
toy_other.children.find_or_create_by(name: "囲碁/将棋")
toy_other.children.find_or_create_by(name: "オセロ/チェス")
toy_other.children.find_or_create_by(name: "人生ゲーム")
toy_other.children.find_or_create_by(name: "野球/サッカーゲーム")
toy_other.children.find_or_create_by(name: "スポーツ")
toy_other.children.find_or_create_by(name: "三輪車/乗り物")
toy_other.children.find_or_create_by(name: "ヨーヨー")
toy_other.children.find_or_create_by(name: "模型制作用品")
toy_other.children.find_or_create_by(name: "鉄道")
toy_other.children.find_or_create_by(name: "航空機")
toy_other.children.find_or_create_by(name: "アマチュア無線")
toy_other.children.find_or_create_by(name: "パチンコ/パチスロ")
toy_other.children.find_or_create_by(name: "その他")

# ---------コスメ・香水・美容 子------------
cosmetics_basemake = cosmetics_perfume_beauty.children.find_or_create_by(name: "ベースメイク")
cosmetics_make_up = cosmetics_perfume_beauty.children.find_or_create_by(name: "メイクアップ")
cosmetics_nail_care = cosmetics_perfume_beauty.children.find_or_create_by(name: "ネイルケア")
cosmetics_perfume = cosmetics_perfume_beauty.children.find_or_create_by(name: "香水")
cosmetics_skin_care = cosmetics_perfume_beauty.children.find_or_create_by(name: "スキンケア/基礎化粧品")
cosmetics_hair_care = cosmetics_perfume_beauty.children.find_or_create_by(name: "ヘアケア")
cosmetics_body_care = cosmetics_perfume_beauty.children.find_or_create_by(name: "ボディケア")
cosmetics_oral_care = cosmetics_perfume_beauty.children.find_or_create_by(name: "オーラルケア")
cosmetics_relaxation = cosmetics_perfume_beauty.children.find_or_create_by(name: "リラクゼーション")
cosmetics_diet = cosmetics_perfume_beauty.children.find_or_create_by(name: "ダイエット")
cosmetics_other = cosmetics_perfume_beauty.children.find_or_create_by(name: "その他")

# ---------コスメ・香水・美容 孫------------
cosmetics_basemake.children.find_or_create_by(name: "ファンデーション")
cosmetics_basemake.children.find_or_create_by(name: "化粧下地")
cosmetics_basemake.children.find_or_create_by(name: "コントロールカラー")
cosmetics_basemake.children.find_or_create_by(name: "BBクリーム")
cosmetics_basemake.children.find_or_create_by(name: "CCクリーム")
cosmetics_basemake.children.find_or_create_by(name: "コンシーラー")
cosmetics_basemake.children.find_or_create_by(name: "フェイスパウダー")
cosmetics_basemake.children.find_or_create_by(name: "トライアルセット/サンプル")
cosmetics_basemake.children.find_or_create_by(name: "その他")

cosmetics_make_up.children.find_or_create_by(name: "アイシャドウ")
cosmetics_make_up.children.find_or_create_by(name: "口紅")
cosmetics_make_up.children.find_or_create_by(name: "リップグロス")
cosmetics_make_up.children.find_or_create_by(name: "リップライナー")
cosmetics_make_up.children.find_or_create_by(name: "チーク")
cosmetics_make_up.children.find_or_create_by(name: "フェイスカラー")
cosmetics_make_up.children.find_or_create_by(name: "マスカラ")
cosmetics_make_up.children.find_or_create_by(name: "アイライナー")
cosmetics_make_up.children.find_or_create_by(name: "つけまつげ")
cosmetics_make_up.children.find_or_create_by(name: "アイブロウペンシル")
cosmetics_make_up.children.find_or_create_by(name: "パウダーアイブロウ")
cosmetics_make_up.children.find_or_create_by(name: "眉マスカラ")
cosmetics_make_up.children.find_or_create_by(name: "トライアルセット/サンプル")
cosmetics_make_up.children.find_or_create_by(name: "メイク道具/化粧小物")
cosmetics_make_up.children.find_or_create_by(name: "美顔用品/美顔ローラー")
cosmetics_make_up.children.find_or_create_by(name: "その他")

cosmetics_nail_care.children.find_or_create_by(name: "ネイルカラー")
cosmetics_nail_care.children.find_or_create_by(name: "カラージェル")
cosmetics_nail_care.children.find_or_create_by(name: "ネイルベースコート/トップコート")
cosmetics_nail_care.children.find_or_create_by(name: "ネイルアート用品")
cosmetics_nail_care.children.find_or_create_by(name: "ネイルパーツ")
cosmetics_nail_care.children.find_or_create_by(name: "ネイルチップ/付け爪")
cosmetics_nail_care.children.find_or_create_by(name: "手入れ用具")
cosmetics_nail_care.children.find_or_create_by(name: "除光液")
cosmetics_nail_care.children.find_or_create_by(name: "その他")

cosmetics_perfume.children.find_or_create_by(name: "香水(女性用)")
cosmetics_perfume.children.find_or_create_by(name: "香水(男性用)")
cosmetics_perfume.children.find_or_create_by(name: "ユニセックス")
cosmetics_perfume.children.find_or_create_by(name: "ボディミスト")
cosmetics_perfume.children.find_or_create_by(name: "その他")

cosmetics_skin_care.children.find_or_create_by(name: "化粧水/ローション")
cosmetics_skin_care.children.find_or_create_by(name: "乳液/ミルク")
cosmetics_skin_care.children.find_or_create_by(name: "美容液")
cosmetics_skin_care.children.find_or_create_by(name: "フェイスクリーム")
cosmetics_skin_care.children.find_or_create_by(name: "洗顔料")
cosmetics_skin_care.children.find_or_create_by(name: "クレンジング/メイク落とし")
cosmetics_skin_care.children.find_or_create_by(name: "パック/フェイスマスク")
cosmetics_skin_care.children.find_or_create_by(name: "ジェル/ゲル")
cosmetics_skin_care.children.find_or_create_by(name: "ブースター/導入液")
cosmetics_skin_care.children.find_or_create_by(name: "アイケア")
cosmetics_skin_care.children.find_or_create_by(name: "リップケア")
cosmetics_skin_care.children.find_or_create_by(name: "トライアルセット/サンプル")
cosmetics_skin_care.children.find_or_create_by(name: "洗顔グッズ")
cosmetics_skin_care.children.find_or_create_by(name: "その他")

cosmetics_hair_care.children.find_or_create_by(name: "シャンプー")
cosmetics_hair_care.children.find_or_create_by(name: "トリートメント")
cosmetics_hair_care.children.find_or_create_by(name: "コンディショナー")
cosmetics_hair_care.children.find_or_create_by(name: "リンス")
cosmetics_hair_care.children.find_or_create_by(name: "スタイリング剤")
cosmetics_hair_care.children.find_or_create_by(name: "カラーリング剤")
cosmetics_hair_care.children.find_or_create_by(name: "ブラシ")
cosmetics_hair_care.children.find_or_create_by(name: "その他")

cosmetics_body_care.children.find_or_create_by(name: "オイル/クリーム")
cosmetics_body_care.children.find_or_create_by(name: "ハンドクリーム")
cosmetics_body_care.children.find_or_create_by(name: "ローション")
cosmetics_body_care.children.find_or_create_by(name: "日焼け止め/サンオイル")
cosmetics_body_care.children.find_or_create_by(name: "ボディソープ")
cosmetics_body_care.children.find_or_create_by(name: "入浴剤")
cosmetics_body_care.children.find_or_create_by(name: "制汗/デオドラント")
cosmetics_body_care.children.find_or_create_by(name: "フットケア")
cosmetics_body_care.children.find_or_create_by(name: "その他")

cosmetics_oral_care.children.find_or_create_by(name: "口臭防止/チケット用品")
cosmetics_oral_care.children.find_or_create_by(name: "歯ブラシ")
cosmetics_oral_care.children.find_or_create_by(name: "その他")

cosmetics_relaxation.children.find_or_create_by(name: "エッセンシャルオイル")
cosmetics_relaxation.children.find_or_create_by(name: "芳香剤")
cosmetics_relaxation.children.find_or_create_by(name: "お香/香炉")
cosmetics_relaxation.children.find_or_create_by(name: "キャンドル")
cosmetics_relaxation.children.find_or_create_by(name: "リラクゼーショングッズ")
cosmetics_relaxation.children.find_or_create_by(name: "その他")

cosmetics_diet.children.find_or_create_by(name: "ダイエット食品")
cosmetics_diet.children.find_or_create_by(name: "エクササイズ用品")
cosmetics_diet.children.find_or_create_by(name: "体重計")
cosmetics_diet.children.find_or_create_by(name: "体脂肪計")
cosmetics_diet.children.find_or_create_by(name: "その他")

cosmetics_other.children.find_or_create_by(name: "健康用品")
cosmetics_other.children.find_or_create_by(name: "看護/介護用品")
cosmetics_other.children.find_or_create_by(name: "救急/衛生用品")
cosmetics_other.children.find_or_create_by(name: "その他")

# -----------家電・スマホ・カメラ 子-----------
home_appliance_phone = home_appliance_smartphone_camera.children.find_or_create_by(name: "スマートフォン/携帯電話")
home_appliance_phone_accessories = home_appliance_smartphone_camera.children.find_or_create_by(name: "スマホアクセサリー")
home_appliance_pc = home_appliance_smartphone_camera.children.find_or_create_by(name: "PC/タブレット")
home_appliance_camera = home_appliance_smartphone_camera.children.find_or_create_by(name: "カメラ")
home_appliance_tv = home_appliance_smartphone_camera.children.find_or_create_by(name: "テレビ/映像機器")
home_appliance_audio = home_appliance_smartphone_camera.children.find_or_create_by(name: "オーディオ機器")
home_appliance_beauty = home_appliance_smartphone_camera.children.find_or_create_by(name: "美容/健康")
home_appliance_air_conditioning = home_appliance_smartphone_camera.children.find_or_create_by(name: "冷暖房/空調")
home_appliance_household_appliances = home_appliance_smartphone_camera.children.find_or_create_by(name: "生活家電")
home_appliance_other = home_appliance_smartphone_camera.children.find_or_create_by(name: "その他")

# -----------家電・スマホ・カメラ 孫-----------
home_appliance_phone.children.find_or_create_by(name: "スマートフォン")
home_appliance_phone.children.find_or_create_by(name: "バッテリー/充電器")
home_appliance_phone.children.find_or_create_by(name: "携帯電話本体")
home_appliance_phone.children.find_or_create_by(name: "PHS本体")
home_appliance_phone.children.find_or_create_by(name: "その他")

home_appliance_phone_accessories.children.find_or_create_by(name: "Android用ケース")
home_appliance_phone_accessories.children.find_or_create_by(name: "iphone用ケース")
home_appliance_phone_accessories.children.find_or_create_by(name: "カバー")
home_appliance_phone_accessories.children.find_or_create_by(name: "イヤホンジャック")
home_appliance_phone_accessories.children.find_or_create_by(name: "ストラップ")
home_appliance_phone_accessories.children.find_or_create_by(name: "フィルム")
home_appliance_phone_accessories.children.find_or_create_by(name: "自撮り棒")
home_appliance_phone_accessories.children.find_or_create_by(name: "その他")

home_appliance_pc.children.find_or_create_by(name: "タブレット")
home_appliance_pc.children.find_or_create_by(name: "ノートPC")
home_appliance_pc.children.find_or_create_by(name: "デスクトップ型PC")
home_appliance_pc.children.find_or_create_by(name: "ディスプレイ")
home_appliance_pc.children.find_or_create_by(name: "電子ブックリーダー")
home_appliance_pc.children.find_or_create_by(name: "PC周辺機器")
home_appliance_pc.children.find_or_create_by(name: "PCパーツ")
home_appliance_pc.children.find_or_create_by(name: "その他")

home_appliance_camera.children.find_or_create_by(name: "デジタルカメラ")
home_appliance_camera.children.find_or_create_by(name: "ビデオカメラ")
home_appliance_camera.children.find_or_create_by(name: "レンズ(単焦点)")
home_appliance_camera.children.find_or_create_by(name: "レンズ(ズーム)")
home_appliance_camera.children.find_or_create_by(name: "フィルムカメラ")
home_appliance_camera.children.find_or_create_by(name: "防犯カメラ")
home_appliance_camera.children.find_or_create_by(name: "その他")

home_appliance_tv.children.find_or_create_by(name: "テレビ")
home_appliance_tv.children.find_or_create_by(name: "プロジェクター")
home_appliance_tv.children.find_or_create_by(name: "ブルーレイレコーダー")
home_appliance_tv.children.find_or_create_by(name: "DVDレコーダー")
home_appliance_tv.children.find_or_create_by(name: "ブルーレイプレーヤー")
home_appliance_tv.children.find_or_create_by(name: "DVDプレーヤー")
home_appliance_tv.children.find_or_create_by(name: "映像用ケーブル")
home_appliance_tv.children.find_or_create_by(name: "その他")

home_appliance_audio.children.find_or_create_by(name: "ポータブルプレーヤー")
home_appliance_audio.children.find_or_create_by(name: "イヤフォン")
home_appliance_audio.children.find_or_create_by(name: "ヘッドフォン")
home_appliance_audio.children.find_or_create_by(name: "アンプ")
home_appliance_audio.children.find_or_create_by(name: "スピーカー")
home_appliance_audio.children.find_or_create_by(name: "ケーブル/シールド")
home_appliance_audio.children.find_or_create_by(name: "ラジオ")
home_appliance_audio.children.find_or_create_by(name: "その他")

home_appliance_beauty.children.find_or_create_by(name: "ヘアドイラヤー")
home_appliance_beauty.children.find_or_create_by(name: "ヘアアイロン")
home_appliance_beauty.children.find_or_create_by(name: "美容機器")
home_appliance_beauty.children.find_or_create_by(name: "電気シェーバー")
home_appliance_beauty.children.find_or_create_by(name: "電動歯ブラシ")
home_appliance_beauty.children.find_or_create_by(name: "その他")

home_appliance_air_conditioning.children.find_or_create_by(name: "エアコン")
home_appliance_air_conditioning.children.find_or_create_by(name: "空気清浄機")
home_appliance_air_conditioning.children.find_or_create_by(name: "加湿器")
home_appliance_air_conditioning.children.find_or_create_by(name: "扇風機")
home_appliance_air_conditioning.children.find_or_create_by(name: "除湿機")
home_appliance_air_conditioning.children.find_or_create_by(name: "ファンヒーター")
home_appliance_air_conditioning.children.find_or_create_by(name: "電気ヒーター")
home_appliance_air_conditioning.children.find_or_create_by(name: "オイルヒーター")
home_appliance_air_conditioning.children.find_or_create_by(name: "ストーブ")
home_appliance_air_conditioning.children.find_or_create_by(name: "ホットカーペット")
home_appliance_air_conditioning.children.find_or_create_by(name: "こたつ")
home_appliance_air_conditioning.children.find_or_create_by(name: "電気毛布")
home_appliance_air_conditioning.children.find_or_create_by(name: "その他")

home_appliance_household_appliances.children.find_or_create_by(name: "冷蔵庫")
home_appliance_household_appliances.children.find_or_create_by(name: "洗濯機")
home_appliance_household_appliances.children.find_or_create_by(name: "炊飯器")
home_appliance_household_appliances.children.find_or_create_by(name: "電子レンジ/オーブン")
home_appliance_household_appliances.children.find_or_create_by(name: "調理機器")
home_appliance_household_appliances.children.find_or_create_by(name: "アイロン")
home_appliance_household_appliances.children.find_or_create_by(name: "掃除機")
home_appliance_household_appliances.children.find_or_create_by(name: "エスプレッソマシン")
home_appliance_household_appliances.children.find_or_create_by(name: "コーヒーメーカー")
home_appliance_household_appliances.children.find_or_create_by(name: "衣類乾燥機")
home_appliance_household_appliances.children.find_or_create_by(name: "その他")

home_appliance_other.children.find_or_create_by(name: "その他")

# --------スポーツ・レジャー 子------------
sports_leisure_golf = sports_leisure.children.find_or_create_by(name: "ゴルフ")
sports_leisure_fishing = sports_leisure.children.find_or_create_by(name: "フィッシング")
sports_leisure_bicycle = sports_leisure.children.find_or_create_by(name: "自転車")
sports_leisure_training = sports_leisure.children.find_or_create_by(name: "トレーニング/エクササイズ")
sports_leisure_baseball = sports_leisure.children.find_or_create_by(name: "野球")
sports_leisure_soccer = sports_leisure.children.find_or_create_by(name: "サッカー/フットサル")
sports_leisure_tennis = sports_leisure.children.find_or_create_by(name: "テニス")
sports_leisure_snowboard = sports_leisure.children.find_or_create_by(name: "スノーボード")
sports_leisure_ski = sports_leisure.children.find_or_create_by(name: "スキー")
sports_leisure_other_sports = sports_leisure.children.find_or_create_by(name: "その他スポーツ")
sports_leisure_outdoor = sports_leisure.children.find_or_create_by(name: "アウトドア")
sports_leisure_other = sports_leisure.children.find_or_create_by(name: "その他")

# --------スポーツ・レジャー 孫------------
sports_leisure_golf.children.find_or_create_by(name: "クラブ")
sports_leisure_golf.children.find_or_create_by(name: "ウエア(男性用)")
sports_leisure_golf.children.find_or_create_by(name: "ウエア(女性用))")
sports_leisure_golf.children.find_or_create_by(name: "バッグ")
sports_leisure_golf.children.find_or_create_by(name: "シューズ(男性用)")
sports_leisure_golf.children.find_or_create_by(name: "シューズ(女性用)")
sports_leisure_golf.children.find_or_create_by(name: "アクセサリー")
sports_leisure_golf.children.find_or_create_by(name: "その他")

sports_leisure_fishing.children.find_or_create_by(name: "ロッド")
sports_leisure_fishing.children.find_or_create_by(name: "リール")
sports_leisure_fishing.children.find_or_create_by(name: "ルアー用品")
sports_leisure_fishing.children.find_or_create_by(name: "ウエア")
sports_leisure_fishing.children.find_or_create_by(name: "釣り糸/ライン")
sports_leisure_fishing.children.find_or_create_by(name: "その他")

sports_leisure_bicycle.children.find_or_create_by(name: "自転車本体")
sports_leisure_bicycle.children.find_or_create_by(name: "ウエア")
sports_leisure_bicycle.children.find_or_create_by(name: "パーツ")
sports_leisure_bicycle.children.find_or_create_by(name: "アクセサリー")
sports_leisure_bicycle.children.find_or_create_by(name: "バッグ")
sports_leisure_bicycle.children.find_or_create_by(name: "工具/メンテナンス")
sports_leisure_bicycle.children.find_or_create_by(name: "その他")

sports_leisure_training.children.find_or_create_by(name: "ランニング")
sports_leisure_training.children.find_or_create_by(name: "ウォーキング")
sports_leisure_training.children.find_or_create_by(name: "ヨガ")
sports_leisure_training.children.find_or_create_by(name: "トレーニング用品")
sports_leisure_training.children.find_or_create_by(name: "その他")

sports_leisure_baseball.children.find_or_create_by(name: "ウェア")
sports_leisure_baseball.children.find_or_create_by(name: "シューズ")
sports_leisure_baseball.children.find_or_create_by(name: "グローブ")
sports_leisure_baseball.children.find_or_create_by(name: "バット")
sports_leisure_baseball.children.find_or_create_by(name: "アクセサリー")
sports_leisure_baseball.children.find_or_create_by(name: "防具")
sports_leisure_baseball.children.find_or_create_by(name: "練習機器")
sports_leisure_baseball.children.find_or_create_by(name: "記念グッズ")
sports_leisure_baseball.children.find_or_create_by(name: "応援グッズ")
sports_leisure_baseball.children.find_or_create_by(name: "その他")

sports_leisure_soccer.children.find_or_create_by(name: "ウェア")
sports_leisure_soccer.children.find_or_create_by(name: "シューズ")
sports_leisure_soccer.children.find_or_create_by(name: "ボール")
sports_leisure_soccer.children.find_or_create_by(name: "アクセサリー")
sports_leisure_soccer.children.find_or_create_by(name: "記念グッズ")
sports_leisure_soccer.children.find_or_create_by(name: "応援グッズ")
sports_leisure_soccer.children.find_or_create_by(name: "その他")

sports_leisure_tennis.children.find_or_create_by(name: "ラケット(公式用)")
sports_leisure_tennis.children.find_or_create_by(name: "ラケット(軟式用)")
sports_leisure_tennis.children.find_or_create_by(name: "ウェア")
sports_leisure_tennis.children.find_or_create_by(name: "シューズ")
sports_leisure_tennis.children.find_or_create_by(name: "ボール")
sports_leisure_tennis.children.find_or_create_by(name: "アクセサリー")
sports_leisure_tennis.children.find_or_create_by(name: "記念グッズ")
sports_leisure_tennis.children.find_or_create_by(name: "応援グッズ")
sports_leisure_tennis.children.find_or_create_by(name: "その他")

sports_leisure_snowboard.children.find_or_create_by(name: "ボード")
sports_leisure_snowboard.children.find_or_create_by(name: "バインディング")
sports_leisure_snowboard.children.find_or_create_by(name: "ブーツ(男性用)")
sports_leisure_snowboard.children.find_or_create_by(name: "ブーツ(女性用)")
sports_leisure_snowboard.children.find_or_create_by(name: "ブーツ(子ども用)")
sports_leisure_snowboard.children.find_or_create_by(name: "ウエア/装備(男性用)")
sports_leisure_snowboard.children.find_or_create_by(name: "ウエア/装備(女性用)")
sports_leisure_snowboard.children.find_or_create_by(name: "ウエア/装備(子ども用)")
sports_leisure_snowboard.children.find_or_create_by(name: "アクセサリー")
sports_leisure_snowboard.children.find_or_create_by(name: "バッグ")
sports_leisure_snowboard.children.find_or_create_by(name: "その他")

sports_leisure_ski.children.find_or_create_by(name: "板")
sports_leisure_ski.children.find_or_create_by(name: "ブーツ(男性用)")
sports_leisure_ski.children.find_or_create_by(name: "ブーツ(女性用)")
sports_leisure_ski.children.find_or_create_by(name: "ブーツ(子ども用)")
sports_leisure_ski.children.find_or_create_by(name: "ビンディング")
sports_leisure_ski.children.find_or_create_by(name: "ウエア(男性用)")
sports_leisure_ski.children.find_or_create_by(name: "ウエア(女性用)")
sports_leisure_ski.children.find_or_create_by(name: "ウエア(子ども用)")
sports_leisure_ski.children.find_or_create_by(name: "ストック")
sports_leisure_ski.children.find_or_create_by(name: "その他")

sports_leisure_other_sports.children.find_or_create_by(name: "ダンス/バレエ")
sports_leisure_other_sports.children.find_or_create_by(name: "サーフィン")
sports_leisure_other_sports.children.find_or_create_by(name: "バスケットボール")
sports_leisure_other_sports.children.find_or_create_by(name: "バドミントン")
sports_leisure_other_sports.children.find_or_create_by(name: "バレーボール")
sports_leisure_other_sports.children.find_or_create_by(name: "スケートボード")
sports_leisure_other_sports.children.find_or_create_by(name: "陸上競技")
sports_leisure_other_sports.children.find_or_create_by(name: "ラグビー")
sports_leisure_other_sports.children.find_or_create_by(name: "アメリカンフットボール")
sports_leisure_other_sports.children.find_or_create_by(name: "ボクシング")
sports_leisure_other_sports.children.find_or_create_by(name: "ボウリング")
sports_leisure_other_sports.children.find_or_create_by(name: "その他")

sports_leisure_outdoor.children.find_or_create_by(name: "テント/タープ")
sports_leisure_outdoor.children.find_or_create_by(name: "ライト/ランタン")
sports_leisure_outdoor.children.find_or_create_by(name: "寝袋/寝具「")
sports_leisure_outdoor.children.find_or_create_by(name: "テーブル/チェア")
sports_leisure_outdoor.children.find_or_create_by(name: "ストーブ/コンロ")
sports_leisure_outdoor.children.find_or_create_by(name: "調理器具")
sports_leisure_outdoor.children.find_or_create_by(name: "食器")
sports_leisure_outdoor.children.find_or_create_by(name: "登山用品")
sports_leisure_outdoor.children.find_or_create_by(name: "その他")

sports_leisure_other.children.find_or_create_by(name: "旅行用品")
sports_leisure_other.children.find_or_create_by(name: "その他")

# ----------ハンドメイド 子---------------
handmade_accessories = handmade.children.find_or_create_by(name: "アクセサリー(女性用)")
handmade_fashion = handmade.children.find_or_create_by(name: "ファッション(小物)")
handmade_accessories = handmade.children.find_or_create_by(name: "アクセサリー/時計")
handmade_daily_necessities = handmade.children.find_or_create_by(name: "日用品/インテリア")
handmade_hobby_toy = handmade.children.find_or_create_by(name: "趣味/おもちゃ")
handmade_kids_baby = handmade.children.find_or_create_by(name: "キッズ/ベビー")
handmade_material = handmade.children.find_or_create_by(name: "素材/材料")
handmade_second = handmade.children.find_or_create_by(name: "二次制作物")
handmade_other = handmade.children.find_or_create_by(name: "その他")

# ----------ハンドメイド 孫---------------
handmade_accessories.children.find_or_create_by(name: "ピアス")
handmade_accessories.children.find_or_create_by(name: "イヤリング")
handmade_accessories.children.find_or_create_by(name: "ネックレス")
handmade_accessories.children.find_or_create_by(name: "ブレスレット")
handmade_accessories.children.find_or_create_by(name: "リング")
handmade_accessories.children.find_or_create_by(name: "チャーム")
handmade_accessories.children.find_or_create_by(name: "ヘアゴム")
handmade_accessories.children.find_or_create_by(name: "アンクレット")
handmade_accessories.children.find_or_create_by(name: "その他")

handmade_fashion.children.find_or_create_by(name: "バッグ(女性用)")
handmade_fashion.children.find_or_create_by(name: "バッグ(男性用)")
handmade_fashion.children.find_or_create_by(name: "財布(女性用))")
handmade_fashion.children.find_or_create_by(name: "財布(男性用)")
handmade_fashion.children.find_or_create_by(name: "ファッション雑貨")
handmade_fashion.children.find_or_create_by(name: "その他")

handmade_accessories.children.find_or_create_by(name: "アクセサリー(男性用)")
handmade_accessories.children.find_or_create_by(name: "時計(女性用))")
handmade_accessories.children.find_or_create_by(name: "時計(男性用))")
handmade_accessories.children.find_or_create_by(name: "その他")

handmade_daily_necessities.children.find_or_create_by(name: "キッチン用品")
handmade_daily_necessities.children.find_or_create_by(name: "家具")
handmade_daily_necessities.children.find_or_create_by(name: "文房具")
handmade_daily_necessities.children.find_or_create_by(name: "アート/写真")
handmade_daily_necessities.children.find_or_create_by(name: "アロマ/キャンドル")
handmade_daily_necessities.children.find_or_create_by(name: "フラワー/ガーデン")
handmade_daily_necessities.children.find_or_create_by(name: "その他")

handmade_hobby_toy.children.find_or_create_by(name: "クラフト/布製品")
handmade_hobby_toy.children.find_or_create_by(name: "おもちゃ/人形")
handmade_hobby_toy.children.find_or_create_by(name: "その他")

handmade_kids_baby.children.find_or_create_by(name: "ファッション雑貨")
handmade_kids_baby.children.find_or_create_by(name: "スタイ/よだれかけ")
handmade_kids_baby.children.find_or_create_by(name: "外出用品")
handmade_kids_baby.children.find_or_create_by(name: "ネームタグ")
handmade_kids_baby.children.find_or_create_by(name: "その他")

handmade_material.children.find_or_create_by(name: "各種パーツ")
handmade_material.children.find_or_create_by(name: "生地/糸")
handmade_material.children.find_or_create_by(name: "型紙/パターン")
handmade_material.children.find_or_create_by(name: "その他")

handmade_second.children.find_or_create_by(name: "ingress")
handmade_second.children.find_or_create_by(name: "クリエイターズ宇宙兄弟")
handmade_second.children.find_or_create_by(name: "シンデレラガールズCPグッズ")

# ----------チケット 子-----------
ticket_music = ticket.children.find_or_create_by(name: "音楽")
ticket_sports = ticket.children.find_or_create_by(name: "スポーツ")
ticket_theater = ticket.children.find_or_create_by(name: "演劇/芸能")
ticket_event = ticket.children.find_or_create_by(name: "イベント")
ticket_movie = ticket.children.find_or_create_by(name: "映画")
ticket_facility_usage_rights = ticket.children.find_or_create_by(name: "施設利用権")
ticket_complimentary_ticket = ticket.children.find_or_create_by(name: "優待券/割引券")
ticket_other = ticket.children.find_or_create_by(name: "その他")

# ----------チケット 孫----------
ticket_music.children.find_or_create_by(name: "男性アイドル")
ticket_music.children.find_or_create_by(name: "女性アイドル")
ticket_music.children.find_or_create_by(name: "韓流")
ticket_music.children.find_or_create_by(name: "国内アーティスト")
ticket_music.children.find_or_create_by(name: "海外アーティスト")
ticket_music.children.find_or_create_by(name: "音楽フェス")
ticket_music.children.find_or_create_by(name: "声優/アニメ")
ticket_music.children.find_or_create_by(name: "その他")

ticket_sports.children.find_or_create_by(name: "サッカー")
ticket_sports.children.find_or_create_by(name: "野球")
ticket_sports.children.find_or_create_by(name: "テニス")
ticket_sports.children.find_or_create_by(name: "格闘技/プロレス")
ticket_sports.children.find_or_create_by(name: "相撲/武道")
ticket_sports.children.find_or_create_by(name: "ゴルフ")
ticket_sports.children.find_or_create_by(name: "バレーボール")
ticket_sports.children.find_or_create_by(name: "バスケットボール")
ticket_sports.children.find_or_create_by(name: "モータースポーツ")
ticket_sports.children.find_or_create_by(name: "ウィンタースポーツ")
ticket_sports.children.find_or_create_by(name: "その他")

ticket_theater.children.find_or_create_by(name: "ミュージカル")
ticket_theater.children.find_or_create_by(name: "演劇")
ticket_theater.children.find_or_create_by(name: "伝統芸能")
ticket_theater.children.find_or_create_by(name: "落語")
ticket_theater.children.find_or_create_by(name: "お笑い")
ticket_theater.children.find_or_create_by(name: "オペラ")
ticket_theater.children.find_or_create_by(name: "サーカス")
ticket_theater.children.find_or_create_by(name: "バレエ")
ticket_theater.children.find_or_create_by(name: "その他")

ticket_event.children.find_or_create_by(name: "声優/アニメ")
ticket_event.children.find_or_create_by(name: "キッズ/ファミリー")
ticket_event.children.find_or_create_by(name: "トークショー")
ticket_event.children.find_or_create_by(name: "その他")

ticket_movie.children.find_or_create_by(name: "邦画")
ticket_movie.children.find_or_create_by(name: "洋画")
ticket_movie.children.find_or_create_by(name: "その他")

ticket_facility_usage_rights.children.find_or_create_by(name: "遊園地/テーマパーク")
ticket_facility_usage_rights.children.find_or_create_by(name: "美術館/博物館")
ticket_facility_usage_rights.children.find_or_create_by(name: "スキー場")
ticket_facility_usage_rights.children.find_or_create_by(name: "ゴルフ場")
ticket_facility_usage_rights.children.find_or_create_by(name: "フィットネスクラブ")
ticket_facility_usage_rights.children.find_or_create_by(name: "プール")
ticket_facility_usage_rights.children.find_or_create_by(name: "ボウリング場")
ticket_facility_usage_rights.children.find_or_create_by(name: "水族館")
ticket_facility_usage_rights.children.find_or_create_by(name: "動物園")
ticket_facility_usage_rights.children.find_or_create_by(name: "その他")

ticket_complimentary_ticket.children.find_or_create_by(name: "ショッピング")
ticket_complimentary_ticket.children.find_or_create_by(name: "レストラン/食事券")
ticket_complimentary_ticket.children.find_or_create_by(name: "フード/ドリンク")
ticket_complimentary_ticket.children.find_or_create_by(name: "宿泊券")
ticket_complimentary_ticket.children.find_or_create_by(name: "その他")

# --------自動車・オートバイ 子---------
bicycle_motorcycle_bicycle = bicycle_motorcycle.children.find_or_create_by(name: "自動車本体")
bicycle_motorcycle_bicycle_tire = bicycle_motorcycle.children.find_or_create_by(name: "自動車タイヤ/ホイール")
bicycle_motorcycle_bicycle_parts = bicycle_motorcycle.children.find_or_create_by(name: "自動車パーツ")
bicycle_motorcycle_bicycle_accessories = bicycle_motorcycle.children.find_or_create_by(name: "自動車アクセサリー")
bicycle_motorcycle_body = bicycle_motorcycle.children.find_or_create_by(name: "オートバイ車体")
bicycle_motorcycle_parts = bicycle_motorcycle.children.find_or_create_by(name: "オートバイパーツ")
bicycle_motorcycle_accessories = bicycle_motorcycle.children.find_or_create_by(name: "オートバイアクセサリー")

# --------自動車・オートバイ 孫---------
bicycle_motorcycle_bicycle.children.find_or_create_by(name: "国内自動車本体")
bicycle_motorcycle_bicycle.children.find_or_create_by(name: "外国自動車本体")

bicycle_motorcycle_bicycle_tire.children.find_or_create_by(name: "タイヤ/ホイールセット")
bicycle_motorcycle_bicycle_tire.children.find_or_create_by(name: "タイヤ")
bicycle_motorcycle_bicycle_tire.children.find_or_create_by(name: "ホイール")
bicycle_motorcycle_bicycle_tire.children.find_or_create_by(name: "その他")

bicycle_motorcycle_bicycle_parts.children.find_or_create_by(name: "サスペンション")
bicycle_motorcycle_bicycle_parts.children.find_or_create_by(name: "ブレーキ")
bicycle_motorcycle_bicycle_parts.children.find_or_create_by(name: "外装、エアロパーツ")
bicycle_motorcycle_bicycle_parts.children.find_or_create_by(name: "ライト")
bicycle_motorcycle_bicycle_parts.children.find_or_create_by(name: "内装品、シート")
bicycle_motorcycle_bicycle_parts.children.find_or_create_by(name: "ステアリング")
bicycle_motorcycle_bicycle_parts.children.find_or_create_by(name: "マフラー・排気系")
bicycle_motorcycle_bicycle_parts.children.find_or_create_by(name: "エンジン、過給器、冷却装置")
bicycle_motorcycle_bicycle_parts.children.find_or_create_by(name: "クラッチ、ミッション、駆動系")
bicycle_motorcycle_bicycle_parts.children.find_or_create_by(name: "電装品")
bicycle_motorcycle_bicycle_parts.children.find_or_create_by(name: "補強パーツ")
bicycle_motorcycle_bicycle_parts.children.find_or_create_by(name: "汎用パーツ")
bicycle_motorcycle_bicycle_parts.children.find_or_create_by(name: "外国自動車用パーツ")
bicycle_motorcycle_bicycle_parts.children.find_or_create_by(name: "その他")

bicycle_motorcycle_bicycle_accessories.children.find_or_create_by(name: "車内アクセサリー")
bicycle_motorcycle_bicycle_accessories.children.find_or_create_by(name: "カーナビ")
bicycle_motorcycle_bicycle_accessories.children.find_or_create_by(name: "カーオーディオ")
bicycle_motorcycle_bicycle_accessories.children.find_or_create_by(name: "車外アクセサリー")
bicycle_motorcycle_bicycle_accessories.children.find_or_create_by(name: "メンテナンス用品")
bicycle_motorcycle_bicycle_accessories.children.find_or_create_by(name: "チャイルドシート")
bicycle_motorcycle_bicycle_accessories.children.find_or_create_by(name: "ドライブレコーダー")
bicycle_motorcycle_bicycle_accessories.children.find_or_create_by(name: "レーダー探知機")
bicycle_motorcycle_bicycle_accessories.children.find_or_create_by(name: "カタログ/マニュアル")
bicycle_motorcycle_bicycle_accessories.children.find_or_create_by(name: "セキュリティ")
bicycle_motorcycle_bicycle_accessories.children.find_or_create_by(name: "ETC")
bicycle_motorcycle_bicycle_accessories.children.find_or_create_by(name: "その他")

bicycle_motorcycle_parts.children.find_or_create_by(name: "タイヤ")
bicycle_motorcycle_parts.children.find_or_create_by(name: "マフラー")
bicycle_motorcycle_parts.children.find_or_create_by(name: "エンジン、冷却装置")
bicycle_motorcycle_parts.children.find_or_create_by(name: "カウル、フェンダー、外装")
bicycle_motorcycle_parts.children.find_or_create_by(name: "サスペンション")
bicycle_motorcycle_parts.children.find_or_create_by(name: "ホイール")
bicycle_motorcycle_parts.children.find_or_create_by(name: "シート")
bicycle_motorcycle_parts.children.find_or_create_by(name: "ブレーキ")
bicycle_motorcycle_parts.children.find_or_create_by(name: "タンク")
bicycle_motorcycle_parts.children.find_or_create_by(name: "ライト、ウィンカー")
bicycle_motorcycle_parts.children.find_or_create_by(name: "チェーン、スプロケット、駆動系")
bicycle_motorcycle_parts.children.find_or_create_by(name: "メーター")
bicycle_motorcycle_parts.children.find_or_create_by(name: "電装系")
bicycle_motorcycle_parts.children.find_or_create_by(name: "ミラー")
bicycle_motorcycle_parts.children.find_or_create_by(name: "外国オートバイ用パーツ")
bicycle_motorcycle_parts.children.find_or_create_by(name: "その他")

bicycle_motorcycle_accessories.children.find_or_create_by(name: "ヘルメット/シールド")
bicycle_motorcycle_accessories.children.find_or_create_by(name: "バイクウエア/装備")
bicycle_motorcycle_accessories.children.find_or_create_by(name: "アクセサリー")
bicycle_motorcycle_accessories.children.find_or_create_by(name: "メンテナンス")
bicycle_motorcycle_accessories.children.find_or_create_by(name: "カタログ/マニュアル")
bicycle_motorcycle_accessories.children.find_or_create_by(name: "その他")

# ----------その他 子------------
other_set = other.children.find_or_create_by(name: "まとめ売り")
other_pet = other.children.find_or_create_by(name: "ペット用品")
other_food = other.children.find_or_create_by(name: "食品")
other_drink = other.children.find_or_create_by(name: "飲料/酒")
other_daily_necessities = other.children.find_or_create_by(name: "日用品/生活雑貨/旅行")
other_untique = other.children.find_or_create_by(name: "アンティーク/コレクション")
other_stationery = other.children.find_or_create_by(name: "文房具/事務用品")
other_office_work = other.children.find_or_create_by(name: "事務/店舗用品")
other_other = other.children.find_or_create_by(name: "その他")

# ----------その他 孫------------
other_pet.children.find_or_create_by(name: "ペットフード")
other_pet.children.find_or_create_by(name: "犬用品")
other_pet.children.find_or_create_by(name: "猫用品")
other_pet.children.find_or_create_by(name: "魚用品/水草")
other_pet.children.find_or_create_by(name: "小動物用品")
other_pet.children.find_or_create_by(name: "爬虫類/両生類用品")
other_pet.children.find_or_create_by(name: "かご/おり")
other_pet.children.find_or_create_by(name: "鳥用品")
other_pet.children.find_or_create_by(name: "虫類用品")
other_pet.children.find_or_create_by(name: "その他")

other_food.children.find_or_create_by(name: "菓子")
other_food.children.find_or_create_by(name: "米")
other_food.children.find_or_create_by(name: "野菜")
other_food.children.find_or_create_by(name: "果物")
other_food.children.find_or_create_by(name: "調味料")
other_food.children.find_or_create_by(name: "魚介類(加工食品)")
other_food.children.find_or_create_by(name: "肉類(加工食品)")
other_food.children.find_or_create_by(name: "その他 加工食品")
other_food.children.find_or_create_by(name: "その他")

other_drink.children.find_or_create_by(name: "コーヒー")
other_drink.children.find_or_create_by(name: "ソフトドリンク")
other_drink.children.find_or_create_by(name: "ミネラルウォーター")
other_drink.children.find_or_create_by(name: "茶")
other_drink.children.find_or_create_by(name: "ウイスキー")
other_drink.children.find_or_create_by(name: "ワイン")
other_drink.children.find_or_create_by(name: "ブランデー")
other_drink.children.find_or_create_by(name: "焼酎")
other_drink.children.find_or_create_by(name: "日本酒")
other_drink.children.find_or_create_by(name: "ビール、発泡酒")
other_drink.children.find_or_create_by(name: "その他")

other_daily_necessities.children.find_or_create_by(name: "タオル/バス用品")
other_daily_necessities.children.find_or_create_by(name: "日用品/生活雑貨")
other_daily_necessities.children.find_or_create_by(name: "洗剤/柔軟剤")
other_daily_necessities.children.find_or_create_by(name: "旅行用品")
other_daily_necessities.children.find_or_create_by(name: "防災関連グッズ")
other_daily_necessities.children.find_or_create_by(name: "その他")

other_untique.children.find_or_create_by(name: "雑貨")
other_untique.children.find_or_create_by(name: "工芸品")
other_untique.children.find_or_create_by(name: "家具")
other_untique.children.find_or_create_by(name: "印刷物")
other_untique.children.find_or_create_by(name: "その他")

other_stationery.children.find_or_create_by(name: "筆記用具")
other_stationery.children.find_or_create_by(name: "ノート/メモ帳")
other_stationery.children.find_or_create_by(name: "テープ/マスキングテープ")
other_stationery.children.find_or_create_by(name: "カレンダー/スケジュール")
other_stationery.children.find_or_create_by(name: "アルバム/スクラップ")
other_stationery.children.find_or_create_by(name: "ファイル/バインダー")
other_stationery.children.find_or_create_by(name: "はさみ/カッター")
other_stationery.children.find_or_create_by(name: "カードホルダー/名刺管理")
other_stationery.children.find_or_create_by(name: "のり/ホッチキス")
other_stationery.children.find_or_create_by(name: "その他")

other_office_work.children.find_or_create_by(name: "オフィス用具一般")
other_office_work.children.find_or_create_by(name: "オフィス家具")
other_office_work.children.find_or_create_by(name: "店舗用品")
other_office_work.children.find_or_create_by(name: "OA機器")
other_office_work.children.find_or_create_by(name: "ラッピング/包装")
other_office_work.children.find_or_create_by(name: "その他")